crypto:
  api:
    mexc:
      get-prices: ${MEXC_PRICES_URI:https://api.mexc.com/api/v3/ticker/price}
  price:
    percentage-change: ${PRICE_CHANGE_PERCENTAGE:3}
    update-interval: ${PRICE_UPDATE_INTERVAL_MS:6000}
telegram:
  bot:
    name: ${TG_BOT_NAME}
    token: ${TG_BOT_TOKEN}
    user-limit: ${TG_USER_LIMIT:1}
spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:crypto-tracking}
